from Tkinter import *
from tkMessageBox import *
root=Tk()
root.config(bg='pink')
root.title('Hotel management -Food world')
global a1
global a2
global a3
global a4
global a5
global a6
a1=0
a2=0
a3=0
a4=0
a5=0
a6=0
Label(root,text="Hotel Managment",font="times 30 bold",bg="pink",height=1,width=20).grid(row=0,column=0,columnspan=6)
p=PhotoImage(file="nwewel.gif")
l=Label(root,image=p).grid(row=1,column=1,rowspan=2,columnspan=4)
Label(root,text="Submitted By :-",font="times 15 bold underline",bg="pink",fg="red").grid(row=8,column=0,sticky='W')
Label(root,text="Name :-",font="times 15 bold",bg="pink",fg="blue").grid(row=9,column=0,sticky='W')
Label(root,text="Ratnesh Kumar Rajak ",font="times 15 bold",bg="pink",fg="blue").grid(row=9,column=5,sticky='W')
Label(root,text="Branch :-",font="times 15 bold",bg="pink",fg="blue").grid(row=10,column=0,sticky='W')
Label(root,text="C.S.E",font="times 15 bold",bg="pink",fg="blue").grid(row=10,column=5,sticky='W')
Label(root,text="Enr.Number  :-",font="times 15 bold",fg="blue",bg="pink").grid(row=11,column=0,sticky='W')
Label(root,text="161B168 ",font="times 15 bold",bg="pink",fg="blue").grid(row=11,column=5,sticky='W')
Label(root,text="Submitted To :-",font="times 15 bold underline",bg="pink",fg="red").grid(row=12,column=5)
Label(root,text="Dr.Mahesh Kumar ",font="times 15 bold",bg="pink",fg="blue").grid(row=13,column=5,sticky='E')
def fun1():
    window=Toplevel()
    window.title('Hotel Management')
    window.config(bg="pink")
    Label(window,text="Welcome in K.K Plaza",font="times 25 italic bold",bd=10,bg="pink",height=1,width=15).grid(row=0,column=1,columnspan=4)
    p=PhotoImage(file="new.gif")
    l=Label(window,image=p).grid(row=1,column=1,rowspan=4,columnspan=4)
    Label(window,text="Food world",font="times 15 italic bold",fg="blue",height=1,width=15).grid(row=4,column=2,columnspan=2)
    def fun():
        x=askyesnocancel('order','Do you want eat anything')
        print x
        if x==True:
            Label(window,text="Click below for the Menu card ",font="times 20 italic bold",bg="pink").grid(row=6,column=1,columnspan=4)
            def fun2():
                Label(window,text="We Have For You",font="times 20 bold italic",bg="orange",fg="blue",height=1,width=15).grid(row=8,column=1,columnspan=4)
                def fun3():
                    hot=Toplevel()
                    hot.title('HOT SOUPS')
                    hot.config(bg='violet')
                    Label(hot,text="HOT SOUPS AVAILABLE ARE  ",font="times 25 bold italic",bg="green",height=1,width=25).grid(row=0,column=1,columnspan=6)
                    Label(hot,text="Items",font="times 20 bold italic",bg="red").grid(row=1,column=0,columnspan=2)
                    Label(hot,text="Price",font="times 20 bold italic",bg="red").grid(row=1,column=5,columnspan=4)
                    v1=IntVar()
                    v2=IntVar()
                    v3=IntVar()
                    v4=IntVar()
                    v5=IntVar()
                    v6=IntVar()
                    Checkbutton(hot,text=' Cream Of Tomato Soup',variable=v1,onvalue='50',bg='violet').grid(row=4,column=1,columnspan=4,sticky='W')
                    Label(hot,text="50",font="times 20 bold italic",bg='violet').grid(row=4,column=5,columnspan=4)
                    Checkbutton(hot,text=' Russian Broth Soup',variable=v2,onvalue='100',bg='violet').grid(row=6,column=1,columnspan=4,sticky='W')
                    Label(hot,text="100",font="times 20 bold italic",bg='violet').grid(row=6,column=5,columnspan=4)
                    Checkbutton(hot,text=' Hot & Sour Veg. & Non Veg',variable=v3,onvalue='75',bg='violet').grid(row=8,column=1,columnspan=4,sticky='W')
                    Label(hot,text="75",font="times 20 bold italic",bg='violet').grid(row=8,column=5,columnspan=4)
                    Checkbutton(hot,text=' Clear Soup Veg. & Non Veg ',variable=v4,onvalue='80',bg='violet').grid(row=9,column=1,columnspan=4,sticky='W')
                    Label(hot,text="80",font="times 20 bold italic",bg='violet').grid(row=9,column=5,columnspan=4)
                    Checkbutton(hot,text=' Sweet Corn Veg. & Non Veg',variable=v5,onvalue='150',bg='violet').grid(row=10,column=1,columnspan=4,sticky='W')
                    Label(hot,text="150",font="times 20 bold italic",bg='violet').grid(row=10,column=5,columnspan=4)
                    Checkbutton(hot,text=' Man Chow Veg. & Non Veg',variable=v6,onvalue='90',bg='violet').grid(row=12,column=1,columnspan=4,sticky='W')
                    Label(hot,text="90",font="times 20 bold italic",bg='violet').grid(row=12,column=5,columnspan=4)
                    def fun3a():
                        global a1
                        a1= v1.get()+v2.get()+v3.get()+ v4.get()+v5.get()+ v6.get()
                        Label(hot,text="Your Total Ammount Rs. "+str (a1),font="times 20 bold italic",bg='violet').grid(row=18,column=0,columnspan=4)
                    Button(hot,text="bill",font="times 20 bold italic",bg='violet',command=fun3a).grid(row=17,column=5,columnspan=4)
                    hot.mainloop()
                def fun4():
                    drink=Toplevel()
                    drink.title('BEVERAGES')
                    drink.config(bg='violet')
                    Label(drink,text=" BEVERAGES AVAILABLE ARE  ",font="times 25 bold italic",bg="green",height=1,width=25).grid(row=0,column=1,columnspan=6)
                    Label(drink,text="Items",font="times 20 bold italic",bg="red").grid(row=1,column=0,columnspan=2)
                    Label(drink,text="Price",font="times 20 bold italic",bg="red").grid(row=1,column=5,columnspan=4)
                    v7=IntVar()
                    v8=IntVar()
                    v9=IntVar()
                    v10=IntVar()
                    v11=IntVar()
                    Checkbutton(drink,text=' Mineral Water',variable=v7,onvalue='18',bg='violet').grid(row=2,column=1,columnspan=4,sticky='W')
                    Label(drink,text="18",font="times 20 bold italic",bg='violet').grid(row=2,column=5,columnspan=4)
                    Checkbutton(drink,text=' Masala Tea/Coffee',variable=v8,onvalue='30',bg='violet').grid(row=6,column=1,columnspan=4,sticky='W')
                    Label(drink,text="30",font="times 20 bold italic",bg='violet').grid(row=6,column=5,columnspan=4)
                    Checkbutton(drink,text=' Milk Shake ',variable=v9,onvalue='30',bg='violet').grid(row=8,column=1,columnspan=4,sticky='W')
                    Label(drink,text="30",font="times 20 bold italic",bg='violet').grid(row=8,column=5,columnspan=4)
                    Checkbutton(drink,text=' Cold coffee',variable=v10,onvalue='80',bg='violet').grid(row=9,column=1,columnspan=4,sticky='W')
                    Label(drink,text="80",font="times 20 bold italic",bg='violet').grid(row=9,column=5,columnspan=4)
                    Checkbutton(drink,text=' Sweet lassi',variable=v11,onvalue='60',bg='violet').grid(row=12,column=1,columnspan=4,sticky='W')
                    Label(drink,text="60",font="times 20 bold italic",bg='violet').grid(row=12,column=5,columnspan=4)
                    def fun4a():
                        global a2
                        a2= v7.get()+v8.get()+v9.get()+ v10.get()+v11.get()
                        Label(drink,text="Your Total Ammount Rs. "+str (a2),font="times 20 bold italic",bg='violet').grid(row=18,column=0,columnspan=4)
                    Button(drink,text="bill",font="times 20 bold italic",bg='violet',command=fun4a).grid(row=17,column=5,columnspan=4)
                    drink.mainloop()
                def fun5():
                    snacks=Toplevel()
                    snacks.title('SNACKS')
                    snacks.config(bg='violet')
                    Label(snacks,text=" SNACKS AVAILABLE ARE ",font="times 25 bold italic",bg="green",height=1,width=25).grid(row=0,column=1,columnspan=6)
                    Label(snacks,text="Items",font="times 20 bold italic",bg="red").grid(row=1,column=0,columnspan=2)
                    Label(snacks,text="Price",font="times 20 bold italic",bg="red").grid(row=1,column=5,columnspan=4)
                    v12=IntVar()
                    v13=IntVar()
                    v14=IntVar()
                    v15=IntVar()
                    Checkbutton(snacks,text=' Aloo Chana Chaat',variable=v12,onvalue='150',bg='violet').grid(row=4,column=1,columnspan=4,sticky='W')
                    Label(snacks,text="150",font="times 20 bold italic",bg='violet').grid(row=4,column=5,columnspan=4)
                    Checkbutton(snacks,text=' Paneer Pakora',variable=v13,onvalue='60',bg='violet').grid(row=5,column=1,columnspan=4,sticky='W')
                    Label(snacks,text="60(2 pcs)",font="times 20 bold italic",bg='violet').grid(row=5,column=5,columnspan=4)
                    Checkbutton(snacks,text=' French Fries',variable=v14,onvalue='90',bg='violet').grid(row=6,column=1,columnspan=4,sticky='W')
                    Label(snacks,text="90",font="times 20 bold italic",bg='violet').grid(row=6,column=5,columnspan=4)
                    Checkbutton(snacks,text=' Pizza ',variable=v15,onvalue='250',bg='violet').grid(row=7,column=1,columnspan=4,sticky='W')
                    Label(snacks,text="250",font="times 20 bold italic",bg='violet').grid(row=7,column=5,columnspan=4)
                    def fun5a():
                        global a3
                        a3= v12.get()+v13.get()+v14.get()+ v15.get()
                        Label(snacks,text="Your Total Ammount Rs. "+str (a3),font="times 20 bold italic",bg='violet').grid(row=18,column=0,columnspan=4)
                    Button(snacks,text="bill",font="times 20 bold italic",bg='violet',command=fun5a).grid(row=17,column=5,columnspan=4)
                    snacks.mainloop()
                def fun6():
                    nonveg=Toplevel()
                    nonveg.title('nonveg')
                    nonveg.config(bg='violet')
                    Label(nonveg,text=" NONVEG'S AVAILABLE ARE",font="times 25 bold italic",bg="green",height=1,width=25).grid(row=0,column=1,columnspan=6)
                    Label(nonveg,text="Items",font="times 20 bold italic",bg="red").grid(row=1,column=0,columnspan=2)
                    Label(nonveg,text="Price",font="times 20 bold italic",bg="red").grid(row=1,column=5,columnspan=4)
                    v16=IntVar()
                    v17=IntVar()
                    v18=IntVar()
                    v19=IntVar()
                    v20=IntVar()
                    Checkbutton(nonveg,text='Chilly Chicken Gravy',variable=v16,onvalue='200',bg='violet').grid(row=2,column=1,columnspan=4,sticky='W')
                    Label(nonveg,text="200",font="times 20 bold italic",bg='violet').grid(row=2,column=5,columnspan=4)
                    Checkbutton(nonveg,text='Hong Kong Chicken',variable=v17,onvalue='250',bg='violet').grid(row=3,column=1,columnspan=4,sticky='W')
                    Label(nonveg,text="250",font="times 20 bold italic",bg='violet').grid(row=3,column=5,columnspan=4)
                    Checkbutton(nonveg,text='Chilly Fish Curry',variable=18,onvalue='180',bg='violet').grid(row=5,column=1,columnspan=4,sticky='W')
                    Label(nonveg,text="180",font="times 20 bold italic",bg='violet').grid(row=5,column=5,columnspan=4)
                    Checkbutton(nonveg,text='Chicken Manchurian',variable=v19,onvalue='150',bg='violet').grid(row=8,column=1,columnspan=4,sticky='W')
                    Label(nonveg,text="150",font="times 20 bold italic",bg='violet').grid(row=8,column=5,columnspan=4)
                    Checkbutton(nonveg,text='Roasted Chicken',variable=v20,onvalue='160',bg='violet').grid(row=6,column=1,columnspan=4,sticky='W')
                    Label(nonveg,text="160",font="times 20 bold italic",bg='violet').grid(row=6,column=5,columnspan=4)
                    def fun6a():
                        global a4
                        a4= v16.get()+v17.get()+v18.get()+ v19.get()+v20.get()
                        Label(nonveg,text="Your Total Ammount Rs. "+str (a4),font="times 20 bold italic",bg='violet').grid(row=18,column=0,columnspan=5)
                    Button(nonveg,text="bill",font="times 20 bold italic",bg='violet',command=fun6a).grid(row=17,column=5,columnspan=4)
                def fun7():
                    veg=Toplevel()
                    veg.title('veg')
                    veg.config(bg='violet')
                    Label(veg,text="VEG'S AVAILABLE ARE",font="times 25 bold italic",bg="green",height=1,width=25).grid(row=0,column=1,columnspan=6)
                    Label(veg,text="Items",font="times 20 bold italic",bg="red").grid(row=1,column=0,columnspan=2)
                    Label(veg,text="Price",font="times 20 bold italic",bg="red").grid(row=1,column=5,columnspan=4)
                    v21=IntVar()
                    v22=IntVar()
                    v23=IntVar()
                    v24=IntVar()
                    v25=IntVar()
                    Checkbutton(veg,text='Paneer Tikka',variable=v21,onvalue='160',bg='violet').grid(row=2,column=1,columnspan=4,sticky='W')
                    Label(veg,text="160",font="times 20 bold italic",bg='violet').grid(row=2,column=5,columnspan=4)
                    Checkbutton(veg,text='Kadhai Paneer',variable=v22,onvalue='190',bg='violet').grid(row=3,column=1,columnspan=4,sticky='W')
                    Label(veg,text="190",font="times 20 bold italic",bg='violet').grid(row=3,column=5,columnspan=4)
                    Checkbutton(veg,text='Veg Manchuriyan',variable=23,onvalue='180',bg='violet').grid(row=5,column=1,columnspan=4,sticky='W')
                    Label(veg,text="180",font="times 20 bold italic",bg='violet').grid(row=5,column=5,columnspan=4)
                    Checkbutton(veg,text='Paneer Do Pyaza',variable=v24,onvalue='150',bg='violet').grid(row=8,column=1,columnspan=4,sticky='W')
                    Label(veg,text="150",font="times 20 bold italic",bg='violet').grid(row=8,column=5,columnspan=4)
                    Checkbutton(veg,text='Chhola sabji',variable=v25,onvalue='160',bg='violet').grid(row=6,column=1,columnspan=4,sticky='W')
                    Label(veg,text="160",font="times 20 bold italic",bg='violet').grid(row=6,column=5,columnspan=4)
                    def fun7a():
                        global a5
                        a5= v21.get()+v22.get()+v23.get()+ v24.get()+v25.get()
                        Label(veg,text="Your Total Ammount Rs. "+str (a5),font="times 20 bold italic",bg='violet').grid(row=18,column=0,columnspan=4)
                    Button(veg,text="bill",font="times 20 bold italic",bg='violet',command=fun7a).grid(row=17,column=5,columnspan=4)
                def fun8():
                    chapati=Toplevel()
                    chapati.title('chapati')
                    chapati.config(bg='violet')
                    Label(chapati,text=" CHAPATI'S AVAILABLE ARE",font="times 25 bold italic",bg="green",height=1,width=25).grid(row=0,column=1,columnspan=6)
                    Label(chapati,text="Items",font="times 20 bold italic",bg="red").grid(row=1,column=0,columnspan=2)
                    Label(chapati,text="Price",font="times 20 bold italic",bg="red").grid(row=1,column=5,columnspan=4)
                    v26=IntVar()
                    v27=IntVar()
                    v28=IntVar() 
                    Checkbutton(chapati,text='Plane Roti(10)',variable=v26,onvalue='8',bg='violet').grid(row=2,column=1,columnspan=4,sticky='W')
                    Label(chapati,text="60",font="times 20 bold italic",bg='violet').grid(row=2,column=5,columnspan=4)
                    Checkbutton(chapati,text='Rumali Roti(5)',variable=v27,onvalue='50',bg='violet').grid(row=5,column=1,columnspan=4,sticky='W')
                    Label(chapati,text="50",font="times 20 bold italic",bg='violet').grid(row=5,column=5,columnspan=4)
                    Checkbutton(chapati,text='Butter Roti(5)',variable=v28,onvalue='12',bg='violet').grid(row=7,column=1,columnspan=4,sticky='W')
                    Label(chapati,text="60",font="times 20 bold italic",bg='violet').grid(row=7,column=5,columnspan=4)
                    def fun8a():
                        global a6
                        a6= v26.get()+v27.get()+v28.get()
                        Label(chapati,text="Your Total Ammount Rs. "+str (a6),font="times 20 bold italic",bg='violet').grid(row=18,column=0,columnspan=4)
                    Button(chapati,text="bill",font="times 20 bold italic",bg='violet',command=fun8a).grid(row=17,column=5,columnspan=4)
                def fun9():
                    bill=Toplevel()
                    bill.title('Bill')
                    bill.config(bg='violet')
                    global a1
                    global a2
                    global a3
                    global a4
                    global a5
                    global a6
                    a=a1+a2+a3+a4+a5+a6
                    Label(bill,text="Your Bill ",font ="times 20 bold italic underline",bg='violet').grid(row=0,column=1,columnspan=4) 
                    Label(bill,text="Your Total Ammount Rs. "+str (a),font="times 20 bold italic",bg='violet').grid(row=1,column=1,columnspan=4)
                    p=PhotoImage(file="thanku.gif")
                    l=Label(bill,image=p).grid(row=4,column=2,rowspan=2,columnspan=2)
                    a=Label(bill,text="Thanks for Visiting Here...  ",bg="violet",font="times 20 bold italic",height=2,width=25,)
                    a.grid(row=8,column=1,columnspan=4)
                Button(window,text="HOT SOUPS",font="times 15 bold italic" ,command=fun3,bg="violet").grid(row=10,column=1,columnspan=2,sticky='W')
                Button(window,text="BEVERAGES",font="times 15 bold italic" ,command=fun4,bg="violet").grid(row=10,column=3,columnspan=2,sticky='W')
                Button(window,text="SNACKS",font="times 15 bold italic",command=fun5,bg="violet" ).grid(row=16,column=1,columnspan=2,sticky='W')
                Button(window,text="NON VEG's",font="times 15 bold italic",command=fun6 ,bg="violet").grid(row=13,column=3,columnspan=2,sticky='W')
                Button(window,text="VEG'S",font="times 15 bold italic",command=fun7,bg="violet" ).grid(row=13,column=1,columnspan=2,sticky='W')
                Button(window,text="CHAPATI",font="times 15 bold italic",command=fun8,bg="violet" ).grid(row=16,column=3,columnspan=2,sticky='W')
                Button(window,text="BILL",font="times 15 bold italic",command=fun9 ).grid(row=20,column=2,columnspan=2,sticky='W') 
            Button(window,text="Menu Card",font="times 20 bold",command=fun2).grid(row=7,column=1,columnspan=4)
        if x==False:
            y=askyesno('order','Do  you want to drink')
            print y
            if y==True:
                Label(window,text="What u want drink",font="times 25 bold italic",bg="green").grid(row=6,column=1,columnspan=4)
                Label(window,text="Items",font="times 20 bold italic",bg="red").grid(row=8,column=1,sticky='W')
                Label(window,text="Price",font="times 20 bold italic",bg="red").grid(row=8,column=4)
                v1=IntVar()
                v2=IntVar()
                v3=IntVar()
                v4=IntVar()
                v5=IntVar()
                Checkbutton(window,text='Coffe',variable=v1,onvalue='50',bg='pink').grid(row=9,column=1,sticky='W')
                Label(window,text="50",font="times 20 bold italic",bg='pink').grid(row=9,column=4)
                Checkbutton(window,text=' Cold Coffe',variable=v2,onvalue='100',bg='pink').grid(row=10,column=1,sticky='W')
                Label(window,text="100",font="times 20 bold italic",bg='pink').grid(row=10,column=4)
                Checkbutton(window,text=' Tea',variable=v3,onvalue='25',bg='pink').grid(row=11,column=1,sticky='W')
                Label(window,text="25",font="times 20 bold italic",bg='pink').grid(row=11,column=4)
                Checkbutton(window,text=' Soup',variable=v4,onvalue='80',bg='pink').grid(row=12,column=1,sticky='W')
                Label(window,text="80",font="times 20 bold italic",bg='pink').grid(row=12,column=4)
                Checkbutton(window,text='Water ',variable=v5,onvalue='20',bg='pink').grid(row=14,column=1,sticky='W')
                Label(window,text="20",font="times 20 bold italic",bg='pink').grid(row=14,column=4)
                def sum():
                    a7=v1.get()+v2.get()+v3.get()+v4.get()+v5.get()
                    Label(window,text="Yours Total Ammount Rs. " +str (a),font="times 20 bold italic",bg='violet').grid(row=20,column=0,columnspan=5)
                    a=Label(window,text="Thanks for Visiting Here...  ",bg="pink",font="times 20 bold italic",height=2,width=25,)
                    a.grid(row=21,column=1,columnspan=4)
                Button(window,text="BILL",font="times 15 bold",fg="blue",command=sum ).grid(row=18,column=2,columnspan=2)
            if y==False:
                a=Label(window,text="Give a Chance to surve you\n Thanks for Visiting Here...  ",bg="pink",font="times 20 bold italic",height=2,width=25,)
                a.grid(row=7,column=1,columnspan=4)
        if x==None:
             a=Label(window,text="Give a Chance to surve you\n Thanks for Visiting Here...  ",font="times 20 bold italic",height=2,width=25,bg='pink')
             a.grid(row=7,column=1,columnspan=4)    
    Button(window,text="Click Here...",command=fun,height=1,width=15).grid(row=5,column=2,columnspan=2)
    window.mainloop()
Button(root,text="Proceed To Project..",fg="blue",font="20",command=fun1).grid(row=20,column=2,columnspan=3)
root.mainloop()
